TESTS WITH ERRORS 
-------------------------------
TESTS FAILED  
test10 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 282, in test10
    self.assertFalse(answer2)
AssertionError: True is not false

test13 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 379, in test13
    self.assertFalse(answer1)
AssertionError: ListOfBindings([(Bindings({}, []), [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), True, [Fact('fact', Statement('healthGoesTo', [Term(Constant('A'))]), True, [], [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), True, [...], [], [])], [])], [], [])])]) is not false

test14 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 402, in test14
    self.assertFalse(answer1)
AssertionError: ListOfBindings([(Bindings({}, []), [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [Fact('fact', Statement('healthGoesTo', [Term(Constant('A'))]), True, [], [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [...], [], [])], [])], [], [])])]) is not false

test4 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 96, in test4
    self.assertFalse(answer4)
AssertionError: ListOfBindings([(Bindings({}, []), [Fact('fact', Statement('goodman', [Term(Constant('A'))]), False, [Fact('fact', Statement('person', [Term(Constant('A'))]), True, [], [Fact('fact', Statement('goodman', [Term(Constant('A'))]), False, [...], [], [Rule('rule', [Statement('wenttoschool', [Term(Constant('A'))])], Statement('doctor', [Term(Constant('A'))]), False, [Fact('fact', Statement('goodman', [Term(Constant('A'))]), False, [...], [], [...])], [Fact('fact', Statement('doctor', [Term(Constant('A'))]), False, [Fact('fact', Statement('wenttoschool', [Term(Constant('A'))]), True, [], [Fact('fact', Statement('doctor', [Term(Constant('A'))]), False, [...], [], [])], [])], [], [])], [])])], [])], [], [Rule('rule', [Statement('wenttoschool', [Term(Constant('A'))])], Statement('doctor', [Term(Constant('A'))]), False, [Fact('fact', Statement('goodman', [Term(Constant('A'))]), False, [Fact('fact', Statement('person', [Term(Constant('A'))]), True, [], [Fact('fact', Statement('goodman', [Term(Constant('A'))]), False, [...], [], [...])], [])], [], [...])], [Fact('fact', Statement('doctor', [Term(Constant('A'))]), False, [Fact('fact', Statement('wenttoschool', [Term(Constant('A'))]), True, [], [Fact('fact', Statement('doctor', [Term(Constant('A'))]), False, [...], [], [])], [])], [], [])], [])])])]) is not false

test5 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 148, in test5
    self.assertFalse(answer3)
AssertionError: True is not false

test9 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 264, in test9
    self.assertFalse(answer2)
AssertionError: ListOfBindings([(Bindings({}, []), [Fact('fact', Statement('rele', [Term(Constant('A')), Term(Constant('B')), Term(Constant('C'))]), False, [Fact('fact', Statement('reld', [Term(Constant('G')), Term(Constant('H')), Term(Constant('I'))]), True, [], [Fact('fact', Statement('rele', [Term(Constant('A')), Term(Constant('B')), Term(Constant('C'))]), False, [...], [], [])], [])], [], [])])]) is not false

-------------------------------
TESTS SKIPPED 
-------------------------------
